server:
  port: 8201

jwt:
  vulnerable:
    secret: "secret-secret-secret-secret-1234"
  secure:
    secret: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
    issuer: auth-service
    audience: orders-service
