services:
  resource-server:
    build: ./resource-server
    container_name: entra-resource-server
    env_file:
      - path: .env
        required: false
    environment:
      AZURE_TENANT_ID: ${AZURE_TENANT_ID:?Define AZURE_TENANT_ID en .env}
      AZURE_API_CLIENT_ID: ${AZURE_API_CLIENT_ID:?Define AZURE_API_CLIENT_ID en .env}
      AZURE_API_AUDIENCE: ${AZURE_API_AUDIENCE:-}
    ports:
      - "8083:8083"
